import buildDeclarationFile from "~utils/buildDeclarationFile.ts";

const configDts = buildDeclarationFile();

configDts.addSingleLineNote(
	"This file is generated by '@matthiesenxyz/astro-feedback' and should not be modified manually.",
);

configDts.addModule("astro-feedback:config", {
	defaultExport: {
		typeDef:
			"import('@matthiesenxyz/astro-feedback/schema').AstroFeedbackOptions",
		singleLineDescription: "Astro Feedback options.",
	},
});

export const configDtsFile = configDts.makeFile();

export default configDtsFile;
