import buildDeclarationFile from '@matthiesenxyz/astrodtsbuilder';
import { name } from '../../package.json';

const dts = buildDeclarationFile();

dts.addSingleLineNote(`This file is generated by '${name}' and should not be modified manually.`);

dts.addModule('astro-feedback:config', {
	defaultExport: {
		typeDef: `import('${name}/schema').AstroFeedbackOptions`,
		singleLineDescription: 'Astro Feedback User Config.',
	},
	typeExports: [
		{
			name: 'AstroFeedbackOptions',
			typeDef: `import('${name}/schema').AstroFeedbackOptions`,
			singleLineDescription: 'Astro Feedback User Config Type.',
		},
	],
});

export const ConfigDTS = dts.makeAstroInjectedType('config.d.ts');

export default ConfigDTS;
