import buildDeclarationFile from '@matthiesenxyz/astrodtsbuilder';
import { name } from '../../package.json';

const dts = buildDeclarationFile();

dts.addSingleLineNote(`This file is generated by '${name}' and should not be modified manually.`);

dts.addModule('astro-feedback:routes', {
	defaultExport: {
		typeDef: `import('${name}/types').RouteMap`,
		singleLineDescription: 'Astro Feedback routes.',
	},
	typeExports: [{ name: 'RouteMap', typeDef: `import('${name}/types').RouteMap` }],
});

export const RouteMapDTS = dts.makeAstroInjectedType('routemap.d.ts');

export default RouteMapDTS;
