import buildDeclarationFile from '@matthiesenxyz/astrodtsbuilder';
import { name } from '../../package.json';

const dts = buildDeclarationFile();

dts.addSingleLineNote(`This file is generated by '${name}' and should not be modified manually.`);

dts.addModule('astro-feedback:routes', {
	defaultExport: {
		typeDef: `import('${name}/types').RouteMap`,
		singleLineDescription: 'Astro Feedback routes.',
	},
	namedExports: [
		{
			name: 'routeGenerator',
			typeDef: `import('${name}/types').RouteGenerator`,
			singleLineDescription: 'Astro Feedback route generator.',
		},
	],
	typeExports: [
		{
			name: 'RouteMap',
			typeDef: `import('${name}/types').RouteMap`,
		},
		{
			name: 'RouteGenerator',
			typeDef: `import('${name}/types').RouteGenerator`,
		},
	],
});

export const RouteMapDTS = dts.makeAstroInjectedType('routemap.d.ts');

export default RouteMapDTS;
