packages:
  - package
  - packages/*
  - playground

catalog:
  "@biomejs/biome": 1.8.3
  "@changesets/cli": ^2.27.8
  "@changesets/config": ^3.0.3
  tsup: ^8.2.4
  typescript: ^5.5.4

catalogs:
  deps:
    "@matthiesenxyz/integration-utils": ^0.2.0
    astro-integration-kit: ^0.16.1
    lucia: ^3.2.0
    lucia-adapter-astrodb: ^0.2.0
    micromatch: ^4.0.8
  astrojs:
    "@astrojs/db": ^0.14.1
    "@astrojs/check": ^0.9.3
    astro: ^4.15.1
  types:
    "@types/micromatch": ^4.0.9
    "@types/node": ^20.16.3